### ISSUE TITLE
Warning on Arduino Nano 33 IoT but it works

### ISSUE THREAD

**Issue by iadegesso** [amirchev/VariableTimedAction#6]
I get a warning when building sketches for my Arduino Nano 33 IoT because this library seems to check if the code is built for an AVR integrated circuit, but despite this warning I get the sketch correctly working on  Arduino Nano 33 IoT! :)

Please remove the warning for the SAMD21 Cortex®-M0+ MCU.

Thanks,

Iade Gesso, PhD

**Comment by amirchev** [comment]
Hi Iade,

I'm not sure I know how to remove that warning. Will look into it.

Alex

**Comment by spotman** [comment]
@amirchev all you need is to set `architectures=*` in `library.properties` file. Your library has no architecture-dependent code so this is a safe change.

**Comment by amirchev** [comment]
@spotman Thank you, it's done.
